apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    environment: dev
    managed-by: kubectl

---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    environment: prod
    managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
     managed-by: ArgoCD