apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-service
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      name: redis
      targetPort: {{ .Values.containerPorts.redis }}
