---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prod-api-gateway-secret
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgBAFkxWEMAmPia3UZOc/PCxFL/BN/nE/gCR9hep0xwZyIkH92KxyE06vhrcgMd5a6pqXXM+M8mmlFszce2Cpn37oktRoiBXWNW2qOQSZD4n7zG0Rlp7ed3s2qmBfR0IFzOHLOq/tH7GGRWqpWQA3ui7TOD7tyIwRldl3avuuhNTD80z9RuhVHtnvh2ZxiDYHv5iT9BhQ2n6IwVR8X+v1bnkm9XmLCwPvYx2ObO6faS36rsl2y4ksDln919LAg5hB01HyTBkdk776nJUSmVR+0ImbtIwfXnjgq5KUMlYIHQB2MpjX4G4GxVK7Q9HbxUqU9p31YVQf9VPZTA30jvM9338gHOYzCTCOYxTTeBA6bsfj6+4km1QWqHX5YjETkFErlk4wdWsuxNFAFu2kaJojyGYTOG92Xp/3Ke8dEJPmVEwtsGnAEHrltucMCZ2PNPI1J1IPxPB/ulWyLXJP+de1MG4xTGNUEpxmqCx0kyq4XLsIx5uyBkUpY/DiogpTqMmmYFogQ9c5TuFqGK49TqxesqE+B51NtW1FtAkjc7WH+/E74aqaaCsbZDGNJvycn0Tef7JaHfqnKghcheRd0XFcwvDOeN9M+/+1JV7Lry5sLdSzARTZs+36Y5KaEuPhUMsD54L0NFX1+5sK4UBPP42e7xWhQ4sgxf3VkGzMd5yVmv24vNR4fwp1C3LnXiBKZTYB2UODcV/tZdJAejr6EkcY9bUn1ibQ4S/1mNU1A==
    JWT_SECRET: AgCl90Jh+5GTQuBLl5v2NII/H/ch+r5AuW9BDFE8cfDF57IYAvqSHtCNkxAcQ1B0a5Obk+KncypuiAqVxJzYXwd0P4Lpyk2M8JtdSiuLDWSxC52FuNyw9r5EyxB9FV4Har3UeaH9obuyfv/c+krpQzJ3Azd1rBuy6Er8kVeqo3P8olnqs6x4T3maFS0xPhRaQ/aKcRJTlmRn7tzRshj0XrMW4rrwDFr5om9yGeTKOWQ/PXD2wq5LpRYN1ryrWokIqIHSa1PjgFO94D43tPWDSTrBX8xlHCKM8TcZCmcyAmBviQGJ28krlAYe/GvC0EvFcp/gGp1E90vb531OIrmg6wOVxDQ2gLbnVdzwW9AKkdfxLPhz9yUXm1E6DCpY3HMhM1fbI+Qfw41jUlwtl6t3mBQefi+mXIFJinPGkPTeJQCGDpphTzGCcg4B67ZKB1+MkRq1ULW330xu4K8dFmgvXy+Fbn4ttZhx4lJEZeyohazJX2+UeeGW3JSGWuDtBzVBv73A+/wct4qo25FuC/0yHeHQ9TNqGH3g0L1NogokJYtCtiW7iGNKn0fohcrL5bdxahUDEQFIPphHHqltBqqX/R/Su12hnnWP5i0qZxlaZarg8XxA39DV29KDzT84bhcFQk5/6LyW9ImZmUA3hTldyYp5chZ8M9wZLWbqH7pUUSE8j6G9LjwmYTcllywh3KJbmRWo7WOkXqWQukqeTQ3I8jpGKt6ROEurMRpz
  template:
    metadata:
      creationTimestamp: null
      name: prod-api-gateway-secret
      namespace: default
