---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dev-api-gateway-secret
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgBQX1G4FVOT0ZCjSHIYXA/FKlsozLWCu36rrRXOvDuvlDDVtM9kYGV2XA91VJeDcdIcdLp6wtT3cIz5WiQEBi2V1Ey6dvX1lGGr91uBMS5+ncPPn525FI+cvoYMWzqb9c4aTKzfGL2jD5keZyX3ix+tZKgrbdJCagPPBVEEw3YaHsmTpfY7b41MnUUO1D2w8eVUG0/G7mcpfVMyr5u5pCZIj/5UH8+4umtZfCbLshA+kK1lLhR6/FMSc/FuoSnRTjbeVnFwqDwmOpOu0eAt7exZG1VV1orZ51om9jmi4dbJ3wj1UAuakCRV+ls/qG7riBjUwmV34MCe9EGdAxXGSvkC5KiNW0b5CV03/AScVQGKV4Jnjz5xk+1v67GtXTKIKY7gIFXFQMGILqOvBQkyE0Lypj2uFkAusLXPgLlaAm2cedhFjyCrtIDLnUBNqL7AGk70uMIOTON2DzQCQ8lEnSjbSo8Jn6BITjlNH1mdB048ngOeVDJaoEwvy4y7WxUCo/XbZcnf0R+OtieDlDQNMr1vpUbPoZ00USBjWOU+S3BZzSdUNOp3EU5ypZmr6GDmX0UYlM+Y6gWJ1DFNQdIkq+7hP2kG83ARu5+k2FaObdQf6hqzOf3ftKJZorRgl+kLG5TtpUWH1hJWlcb9Yishc5OTQ5DJ9UDN3W9tY0g+7kLblINErjpcpl63tZF2/225KkfFyZ6xvFlwQAmFZY/KYYZgcZfLl8O6Z+s6
    JWT_SECRET: AgAVeDaj1XmAEM/g/zSUGwnauy5SWj5vj57ullKmoWQ/BYylN0HnRvDkJUVhw2E1UjxCAVt9xmzacCjHa0KpeO/OIAnL77/P5YI5QTTvLw/BxC+QmwPB3lkSU0sLPnD/vV88FrI+899xSVk6es6zWeEkSSIPnb0GRfdw1lP+NK3VkEnm3i1jbjdtegVN8j2wMuya2w+jE+KhJbkC5rDGKblEHqV9oCZ9qFooC/xr1oHamovx1E3F/7mkDMtddnkaWGtn+LaQ1TFPuW+N7dXqxpkB9ftCFfhMFfRizyytwm7x6Mk333Ro8B8rpVyR+Jwx5vP8dfOc/a27zXDk2UQ5ZSmLfiJkxaq9d6BUSOGqgfhjw9otA7ZPr2G7sDs+Yr56ttCE/UEgA7HYQB13MoBEqQedF6MfJV90tl12T64n3/3FYE+KWetU4hls+LCvIAiUQew/YobGKEbYAQYbxSR9/g64jA2EKHGfkPpDoDp4UWhR4EeOOz0N4DG4be0juUbZWExKHxeyU9cjUTCfuPv1m+l0Ule7TsrjQNamTfGSmfcSHhnKFlfhhYtpcwUxCoJaAVtxymKMeQiUjp7th8akyjzugRwE/0H2le8yCNJovnIJIgrF43AYtrwM5M9c5WADjdi6Yyzz7CwJP7PbtghLz0g3kf0YJixYTap/CEUtuzfZF0Jc2ghcOdR6V2dLujWqlE6Fiu/alu/AwqziAYPuJ+WVsjKmNg3vr5g=
  template:
    metadata:
      creationTimestamp: null
      name: dev-api-gateway-secret
      namespace: default
