---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dev-auth-service-secret
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgAf4KFBLya2loO0TYh/7OEt4nmooj5MSzHQU7iZTCa0/cLq96tIdrNPFoXpQ255flTiwFdIzAvO1TlSelmnsSTsUnUpRBxzfUyrUuV3oiYf7f6PrBgwyPGLen6uJfm+RicOIZ7pB2Cu1UwFGChjEDyciPtE8hzMCojdLzpQdc6z07cA/yk4PxDjKSyhIZY5agUWQH0VhlFi+64tRV2NAnJUU/D1vWjWj1fk3ZwEMXIBJQif9NACcnii3/ZjcdEBozq/tIWrcTvkP+saPQuUJLkX5JoRTEtSZhNZEJNaCmxy0W83ekZDYAvHqny3zKpiJ6s8ddjsba54UQQkwYi7ZWBN3cPhTjs7XaZIWclqpwii4PkKwcSGXnTJUvuoG6t2Nz5FrAXbryFsUDoXj8RoY+tQylOVVAOyXdIZU2DSjx6sutnb4+fBajprPgLuACvcbzovPnCUWPM5Kti/zpDUMA8nass/sl24krJp2iAPCRW3vkjrYwRLwfkXVdIF1AOm24XqnUWmDsGa7jg7NlEUEDAqya/YpbkBgMixdReXjo4Ibyr45SgvIm4EcBWwq8lVdGYMYLWkR/FJcAyyEynvLT8pbjSXwTWNcXtBAxL9JSeFJw9CChsSvTUOHdmWnYQeZKp7tNLHtzLWg/b8dNQWHlvRr1BP7mjmgZ0uw37CA7ZhiQe+/RZF0GTe5ici9Kj3kx+/hmkrlRsv3dV/LiAev5/lAKJWdUhT2EOQ
    JWT_SECRET: AgBOUVAo3IvQCqa6X9NZZTpqjn0OOHDOOloNofOj9kDDuLUJLz0mnLR5/O6/91k3+sW5ycr406ufquHaUDcixnppxVMRge4JkCJtcVolzAeU0y44nKf4MlOTvnOijcEHIHFPyxLcMfLTdp66+T8JRSLaDpophZmxCD7jq+Dd+L86f+phU8x2fWOmg0/hn/4Og14qlrnI8sOVgRXNCcbbQjrycAnaCbQdKFf45oTeqa4ccAN3w/Zj88HUXS3vcu5uwQ3nXlj/B3BTsJlV13+xfItNGGKkz6/pkNNzLbXHmncgvawwhxsG0vbzFQlz7hA1SCFG3OefQioAgkS4G1KrChj3Y54zmJIQvjtICPvSSRnbQMVS+ZXwvJZYFZvZL2b7Ma542l+w+4udXTAgugu5VYyEWreJMD8YFMCgqGzSuzsf6R1NC+wcFmcHDZjMybD26L7JRjlG1S1aSlllExTHNqNdNj+xSRc6SF2V/elG+jjW6J7smlBz4NXAIn7vYLi65f2lhsCctZ4FNprc0c41Cw+HOUWmzWi9mi4WU76QzzqqKgYF1WEwICyzXP73O/Ni3kW/Xbm19oXsR2RgSXn7wmypSej80zxWLwEQnSqlSBFPgsNkizFYaJmoObwUZLfHubkHCMOqh+zS7M/sI+U40+ZvGV6nTN1zh6ZX3Ym73zNjYD0m9ValaMg6Ujtj/bm4vRkgLym50D2kmEIPU1a28FDtlSNIlbGSFZw=
  template:
    metadata:
      creationTimestamp: null
      name: dev-auth-service-secret
      namespace: default
