---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prod-auth-service-secret
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgCvwtJP2RMR7LRK5206dlZj+RAId32JVj2L1fcG9dgWAiknvn80HtNXlYmlhlBt/A6VuvnhBnlpxPHldxhF0govNIkYfelyXTbLzIPE2Eq+JXlX6YQOBnbJCRi0k/M7pDw31oN5mk40AErZbBc2uVD58fqY2iRkpih5F7pcOuM8M26tZCs5fOvsTm8gG9X3e4XfZuH96qEzc8IWb0np5ZFzdyEneKn+miuYOFYE+puOu8oIQQr//hj03MZ0smxNClmoLxommKrQfptT8efRdwsKsuXGiVln4if5+Cg9siIzBi0jC4ouO3n77KnyC7IzdoHw+aanLF8sjGSfYYTPZUOz/IEI+K+vwdpOhM1M2JvRgCbuWCuU/71qymIEkZfspYUWeEsEv7Kd0k+l41MlOWqN5vXt1/hSIrS1e95Y32YNPfXmhFa2T/s9kA6A4DyY7Sd9czv1VgTlKVAQabZ5S/+JiNBO1YZ25wbixA7tPRpkKptM5n+7dGG9MDz6/wyKxk+MO+adU6ftamTsAwwFpf1sOm0n/Z5FxkKzFZxpRkS59Z5FjUKmXnDpJ9p/DBIeftFWyRd5+8vMZFby9tXITxv3B3/TEVCOwjilqAafBaZAR0J5vUy4g8q2WYacsqQazUZqtkuIZF9cV1xSc5KR8j1pXAalrBwJEH39+PeqByS0KosV+yMJSAd/Gq4jVZJtXB4IpHS7sy4tkOaysHl1+xcwIhinC+Go5jaapQ==
    JWT_SECRET: AgCYPlis95XGOnpx4G8AxXKE+Lp+CGhXWKJ2NHRaAMboHRTSc6y3cQPcM8LX5+VNaoxVuph6CtLXa+EojycAK3bmwXcHUtWUXo7kuH+MwsTprQefxFWbUf70ays6m2LwR2nZ98v47HcFYl+aN2SdGl4FO7zJHXzjNvqETl1ohOEwPWm6aGt21zP6EDTxByToneAhp7nfQZ8LEymc1aeDQdIFadLXf9eFXLjsldsec3mLcEiRLNqRpek0xprWKYgeH842y5gVc2U/uYt7e9mzFyLgjnUO3er0hAq8PriMCWglg9xxVzzsUV5OTxs5Saqh9TypbijhoHNga0tldtPhUVkq43xr3L6NBozCPaZ5ZLelMnN0tmZLrR6tCuLyPSJAvKb7zAE4KHY7Ao8iQu8uwSFF0G5Ru21QGpWF/S7g/UUu7Sep1VOOuTark3sahqmN6Jsmt9ysRviVzhTh5qb7l6npjCDLPWx+xOXc7+Mz+e51Rdq5ktcr2doiSo04MrpXAW0KeHEmqopgsNLDe1K0lfi4/TXPzXJhnqTPS22r5J5Q8mHZTCpPch/Vkfw5EtxzW6Kp0AcYP+HQgEVOwx1mvHI9zkMGC+IjK+WIZm4RAliP8zQpuMZXicGusJr/UnZ9tqWzdgrMXornuNc586KlQ1v8WqD1OECLhETNRTooRRfcDGmyXoR1X9UeNZQmOeMPCHH9AbzzJsTBy4VXBP5DJcU5p+l4390GJaq5
  template:
    metadata:
      creationTimestamp: null
      name: prod-auth-service-secret
      namespace: default
