apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-gateway.fullname" . }}-deployment
  labels:
    {{- include "api-gateway.labels" . | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "api-gateway.labels" . | nindent 8}}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8}}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8}}
      {{- end }}
      containers:
        - name: api-gateway
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPorts.http }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "api-gateway.fullname" . }}-configmap
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-gateway.fullname" . }}-secret
                  key: JWT_SECRET
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-gateway.fullname" . }}-secret
                  key: DB_PASSWORD



