apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - service: auth-service
        env: dev
        namespace: dev
      - service: auth-service
        env: prod
        namespace: prod
      - service: api-gateway
        env: dev
        namespace: dev
      - service: api-gateway
        env: prod
        namespace: prod
      - service: postgres
        env: dev
        namespace: dev
      - service: postgres
        env: prod
        namespace: prod
  template:
    metadata:
      name: 'sealed-{{service}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Samessprog/K8S-web-app
        targetRevision: HEAD
        path: sealed-secrets
        directory:
          include: '{{service}}-{{env}}.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
